<div class="container">
<div class="row">

	<div class="col-sm-3">
		<h1>All Rss</h1>
	</div>
	<!-- <div class="col-sm-2">
   <h4><a href="add" class="btn btn-success">Add Rss</a></h4>
  </div> -->
</div>
<div class="table-responsive">
			<table class="table table-striped">
			<tr>
                <th>Rss Name</th>
				<th>Rss Description</th>
				<th>Rss URL</th>
				<th style="width:200px" width="200">Actions</th>

			</tr>

			<?php if($this->rss) {

			for($i=0; $i<count($this->rss); $i++){?>
				<tr id='row'>
				<td><?php echo $this->rss[$i]['rName']; ?></td>
				<td><?php echo $this->rss[$i]['rDesc']; ?></td>
				<td><?php echo $this->rss[$i]['rUrl']; ?></td>
				<td>

<a href="rss/rssid/<?php echo $this->rss[$i]['id']; ?>" class=" btn btn-primary" onclick="editUser('.$user_id.')" id="edit'.$user_id.'"><i class="fa fa-pencil-square-o fa-3x">View</i></a>
<a href="edit/rssid/<?php echo $this->rss[$i]['id']; ?>" class="btn btn-success" onclick="deleteUser('.$user_id.')" id="delete'.$user_id.'"><i class="fa fa-trash-o fa-3x"></i>Edit</a>
<a href="delete/rssid/<?php echo $this->rss[$i]['id']; ?>" class="btn btn-danger"><i class="fa fa-eye fa-3x">Delete</i></a>


				</td>
				</tr><?php
					}
}?>

		</table>
		</div>
		</div>
